out with the old in with the new

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,24 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo '🏗️👷 Styling, testing and building your project before committing'
+echo '🏗️👷 Preparing to commit: Formatting, testing, and building your project...'
 
-# Check ESLint Standards
-yarn run check-lint ||
+# Check Lint
+yarn run lint ||
 (
-        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+        echo '😤🏀👋😤 Lint Check Failed! 🙅‍♂️
+                Make the required changes listed above, add the changes, and try to commit again.'
         false; 
 )
 
-# Check tsconfig standards
-yarn run check-types ||
-(
-    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
-            Are you seriously trying to write that? Make the changes required above.'
-    false;
-)
-
 # If everything passes... Now we can commit
-echo '🤔🤔🤔🤔... Alright... Code looks good to me... I am committing this now. ✅✅✅✅'
-
+echo '🤔🤔🤔🤔... All good! Committing now. 🚀'
